CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(32) NOT NULL,
	`clientName` varchar(160) NOT NULL,
	`clientPhone` varchar(40) NOT NULL,
	`clientType` enum('particular','oficina','empresa_flota') NOT NULL DEFAULT 'particular',
	`companyName` varchar(160),
	`vehicleType` enum('auto','camioneta') NOT NULL,
	`vehicleModel` varchar(120) NOT NULL,
	`licensePlate` varchar(32),
	`servicePrice` int NOT NULL,
	`cityZone` enum('Asuncion','Luque','Mariano Roque Alonso','San Lorenzo') NOT NULL,
	`address` text NOT NULL,
	`addressReference` text,
	`scheduledDate` varchar(10) NOT NULL,
	`timeSlot` varchar(20) NOT NULL,
	`appointmentStatus` enum('pendiente','confirmado','en_camino','en_proceso','finalizado','cancelado') NOT NULL DEFAULT 'pendiente',
	`notes` text,
	`source` enum('interno_manual','portal_cliente') NOT NULL DEFAULT 'interno_manual',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`),
	CONSTRAINT `appointments_code_unique` UNIQUE(`code`)
);
